java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/rpe/github-actions-backend:latest'
  ingressHost: rpe-github-actions-backend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rpe
  environment:
