version: '2.1'

services:
  github-actions-backend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/rpe/github-actions-backend
    ports:
      - $SERVER_PORT:$SERVER_PORT
